language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.8.0
  - DJANGO=1.9.0
  - DJANGO=1.10.0
  - DJANGO=1.11.0
install:
  - pip install -q Django~=$DJANGO
script:
  - DJANGO_SETTINGS_MODULE=tests.settings python setup.py test

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0.0
